### ISSUE TITLE
Use systemd drop in instead of overwritting /usr/lib/systemd/system service

### ISSUE THREAD

**Issue by tomleb** [keylime/ansible-keylime-tpm-emulator#39]
As mentioned in this blog post: https://blog.verbum.org/2020/08/22/immutable-%e2%86%92-reprovisionable-anti-hysteresis/ ansible is overwriting a service that may be then overwritten by a OS upgrade. This could lead to the frustrating following scenario:
- Provision system
- Install things (including keylime)
- ⌛ Time passes
- Apply OS updates (not on by default), then keylime breaks for a not obvious reason

For example, here: https://github.com/keylime/ansible-keylime-tpm-emulator/blob/master/roles/ansible-keylime-tpm20/tasks/ibm-tpm.yml#L46.

```yaml
- name: Change TCTI to emulator
  lineinfile:
    path: /usr/lib/systemd/system/tpm2-abrmd.service
    regexp: '^ExecStart='
    line: ExecStart=/usr/sbin/tpm2-abrmd --tcti=mssim

- name: Comment out ConditionPathExistsGlob
  lineinfile:
    path: /usr/lib/systemd/system/tpm2-abrmd.service
    regexp: '^ConditionPathExistsGlob='
    line: '# ConditionPathExistsGlob=/dev/tpm*'
```
